---
name: LottoPlugin
version: 1.0.0
main: Nyrok\LottoPlugin\Main
api: [ 3.0.0 ]
commands:
  lotto:
    description: See timeleft before next lotto. Powered by @Nyrok10 on Twitter.
    aliases:
    - loto
  ticket:
    description: Buy tickets to play at lotto. Powered by @Nyrok10 on Twitter.
depend:
  - EconomyAPI
...
