---
name: LottoPlugin
version: 1.0.0
main: Nyrok\LottoPlugin\Main
api: [ 4.0.0 ]
commands:
  lotto:
    description: Voir le temps restant du lotto. Powered by @Nyrok10 on Twitter.
    aliases:
    - loto
    permission: lotto
  ticket:
    description: Acheter des tickets pour jouer au lotto. Powered by @Nyrok10 on Twitter.
    permission: ticket
permissions:
  lotto:
    description: Voir le temps restant du lotto.
    default: true
  ticket:
    description: Acheter des tickets pour jouer au lotto.
    default: true
depend:
  - EconomyAPI
...
