---
name: LottoPlugin
version: 1.0.0
main: Nyrok\LottoPlugin\Main
api: [ 3.0.0 ]
commands:
  lotto:
    description: Voir le temps restant du lotto. Powered by @Nyrok10 on Twitter.
  ticket:
    description: Acheter des tickets pour jouer au lotto. Powered by @Nyrok10 on Twitter.
depend:
  - EconomyAPI
...
